In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression as LR

In [2]:
train = pd.read_csv("obent/train.csv")

In [3]:
test= pd.read_csv("obent/test.csv")
sample = pd.read_csv("obent/sample.csv",header=None)

In [4]:
train.head()


datetime    y week  soldout        name  kcal remarks event  payday  \
0  2013-11-18   90    月        0    厚切りイカフライ   NaN     NaN   NaN     NaN   
1  2013-11-19  101    火        1     手作りヒレカツ   NaN     NaN   NaN     NaN   
2  2013-11-20  118    水        0  白身魚唐揚げ野菜あん   NaN     NaN   NaN     NaN   
3  2013-11-21  120    木        1      若鶏ピリ辛焼   NaN     NaN   NaN     NaN   
4  2013-11-22  130    金        1    ビッグメンチカツ   NaN     NaN   NaN     NaN   

  weather precipitation  temperature  
0      快晴            --         19.8  
1      快晴            --         17.0  
2      快晴            --         15.5  
3      快晴            --         15.2  
4      快晴            --         16.1

In [5]:
trainX=train["temperature"]
y = train["y"]

In [6]:
trainX

0      19.8
1      17.0
2      15.5
3      15.2
4      16.1
5      14.6
6      17.9
7      14.7
8      17.7
9      12.1
10     13.8
11     13.9
12     13.5
13     13.8
14     14.9
15      9.1
16      7.1
17     11.0
18     12.3
19     13.9
20     11.3
21     10.8
22      7.8
23      6.8
24      8.4
25     11.5
26      8.0
27      7.3
28      7.3
29      9.8
       ... 
177    32.2
178    33.3
179    33.3
180    33.0
181    33.1
182    26.0
183    26.2
184    21.0
185    21.6
186    25.1
187    23.4
188    29.1
189    26.7
190    26.5
191    30.2
192    23.1
193    26.8
194    25.0
195    21.9
196    27.3
197    28.8
198    25.0
199    24.1
200    23.6
201    25.2
202    24.8
203    25.4
204    27.1
205    26.6
206    28.1
Name: temperature, dtype: float64

In [7]:
testX = test["temperature"]

In [8]:
trainX= trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

In [9]:
trainX

array([[ 19.8],
       [ 17. ],
       [ 15.5],
       [ 15.2],
       [ 16.1],
       [ 14.6],
       [ 17.9],
       [ 14.7],
       [ 17.7],
       [ 12.1],
       [ 13.8],
       [ 13.9],
       [ 13.5],
       [ 13.8],
       [ 14.9],
       [  9.1],
       [  7.1],
       [ 11. ],
       [ 12.3],
       [ 13.9],
       [ 11.3],
       [ 10.8],
       [  7.8],
       [  6.8],
       [  8.4],
       [ 11.5],
       [  8. ],
       [  7.3],
       [  7.3],
       [  9.8],
       [ 10.9],
       [  5.1],
       [  5.8],
       [  2.9],
       [  7. ],
       [  7.8],
       [  6.5],
       [ 10.4],
       [  7.4],
       [  8.5],
       [ 10.1],
       [  5.1],
       [ 12.6],
       [ 10.3],
       [ 15.3],
       [ 14.1],
       [ 15.9],
       [  3.8],
       [  3. ],
       [  4.2],
       [  5.5],
       [  7.8],
       [  6.3],
       [  6.4],
       [  1.2],
       [ 11.6],
       [  6.8],
       [  7.3],
       [  5.4],
       [  8.5],
       [  6.6],
       [ 10.5],
       [

In [10]:
model1 = LR()

In [11]:
model1.fit(trainX,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
model1.coef_

array([-2.5023821])

In [13]:
model1.intercept_

134.79948383749928

In [14]:
pred = model1.predict(testX)

In [15]:
pred

array([  84.25136537,   74.99255159,   62.9811175 ,   80.99826864,
         79.49683938,   76.49398085,   78.49588653,   69.48731097,
         67.73564349,   95.76232304,   88.25517673,   77.24469548,
         74.99255159,   84.25136537,   96.01256125,   98.01446693,
         88.00493852,   77.99541011,   87.00398568,   85.75279463,
         85.75279463,   87.75470031,   87.5044621 ,   94.7613702 ,
         86.75374747,   84.50160358,   81.74898327,   98.01446693,
         98.76518156,   86.00303284,   95.26184662,   99.01541977,
         94.51113199,   97.51399051,  108.52447176,   97.51399051,
        106.27232787,  111.7775685 ,   97.01351409,   96.51303767])

In [16]:
sample.head()

0   1
0  2014-10-1  24
1  2014-10-2  71
2  2014-10-3  25
3  2014-10-6  32
4  2014-10-7  60

In [17]:
sample[1]=pred

In [18]:
sample.head()

0          1
0  2014-10-1  84.251365
1  2014-10-2  74.992552
2  2014-10-3  62.981117
3  2014-10-6  80.998269
4  2014-10-7  79.496839